name: dotnet-ci-branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore MineSweeper
    - name: Build
      run: dotnet build --no-restore MineSweeper
    - name: Test
      run: dotnet test --no-build --verbosity normal MineSweeper
    - name: List files
      run: | 
        cd ./MineSweeper/MineSweeper/bin
        ls
#    - name: Upload a Build Artifact
#      uses: actions/upload-artifact@v3.1.0
#      with:
#        name: minesweeper-artifact
#        path: ./MineSweeper/MineSweeper/bin/Release/net5.0
