name: "Minesweeper"

on:
  issues:
    types: [opened]

jobs:
  play:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'revealcell|') || startsWith(github.event.issue.title, 'flagcell|')
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dynamic-readme-profile
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: ${{ github.event.issue.title }}
        split-by: '|'  
    - name: Execute
      run: | 
        echo "Command: ${{ steps.split.outputs._0 }} - Cell(${{ steps.split.outputs._1 }}, ${{ steps.split.outputs._2 }})"
        cd ./MineSweeper/MineSweeper/bin/Release/net5.0
        dotnet run --configuration Release --verbosity m --project ../../../MineSweeper.csproj -- ${{ steps.split.outputs._0 }} ${{ steps.split.outputs._1 }} ${{ steps.split.outputs._2 }}
